### ISSUE TITLE
bugzilla.mozilla.org bug gives a backtrace

### ISSUE THREAD

**Issue by mcepl** [mcepl/testissuesimport#17]
{{{
info: config keys = matches, skipMatches, gJSONData, logger, 
info: url = https://bugzilla.mozilla.org/show_bug.cgi?id=403900
info: bugNo = 403900
error: An exception occurred.
Traceback (most recent call last):
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/errors.js", line 49, in 
    return callback.apply(this, arguments);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/tab-browser.js", line 257, in eventHandler
    callback(event.target.defaultView);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/main.js", line 155, in 
    var curPage = new construct(window, config);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/rhbzpage.js", line 25, in RHBugzillaPage
    BZPage.call(this, win, config);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/bzpage.js", line 107, in BZPage
    this.generateButtons();
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/bzpage.js", line 419, in generateButtons
    this.createNewButton(newId, firstChr === "+", pkg, cmdIdx);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/bzpage.js", line 383, in createNewButton
    originalLocation.parentNode.insertBefore(newButton, originalLocation);
TypeError: originalLocation is null
}}}

**Comment by mcepl** [comment]
_Imported from trac issue 17.  Created by mcepl on 2010-07-04T17:07:30, last modified: 2010-07-27T20:59:50_

**Comment by mcepl** [comment]
_Trac comment by mcepl on 2010-07-15 12:37:56:_

Fixed in [4bc527b]

**Comment by mcepl** [comment]
_Trac comment by  on 2010-07-27 20:59:50:_

Milestone Guadec2010 deleted
