### ISSUE TITLE
test with Firefox 4

### ISSUE THREAD

**Issue by mcepl** [mcepl/testissuesimport#36]
that's it

**Comment by mcepl** [comment]
_Imported from trac issue 36.  Created by mcepl on 2010-07-28T16:47:00, last modified: 2010-07-28T23:05:41_

**Comment by mcepl** [comment]
_Trac comment by mcepl on 2010-07-28 16:53:49:_

{{{
(jetpack-sdk)johanka:bugzilla-triage$ error: An exception occurred.
Traceback (most recent call last):
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/errors.js", line 49, in 
    return callback.apply(this, arguments);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/tab-browser.js", line 258, in eventHandler
    callback(event.target.defaultView);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/main.js", line 125, in 
    var curPage = new construct(window, config);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/rhbzpage.js", line 25, in RHBugzillaPage
    BZPage.call(this, win, config);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/bzpage.js", line 106, in BZPage
    this.CCList = this.getCCList();
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/bzpage.js", line 959, in getCCList
    outCCList = [];
ReferenceError: assignment to undeclared variable outCCList


}}}

**Comment by mcepl** [comment]
_Trac comment by mcepl on 2010-07-28 16:54:59:_

Apparently we are using

**Comment by mcepl** [comment]
_Trac comment by mcepl on 2010-07-28 17:18:06:_

I've asked for strict mode and finally Firefox 4 delivers it ;)

**Comment by mcepl** [comment]
_Trac comment by mcepl on 2010-07-28 23:05:41:_

Fixed in [b7ea22f4].
