### ISSUE TITLE
bugzilla.redhat.com cannot find originalLocation after upgrade to 3.6

### ISSUE THREAD

**Issue by mcepl** [mcepl/testissuesimport#40]
{{{
error: An exception occurred.
Traceback (most recent call last):
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/errors.js", line 49, in 
    return callback.apply(this, arguments);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/tab-browser.js", line 258, in eventHandler
    callback(event.target.defaultView);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/main.js", line 125, in 
    var curPage = new construct(window, config);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/rhbzpage.js", line 25, in RHBugzillaPage
    BZPage.call(this, win, config);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/bzpage.js", line 123, in BZPage
    this.generateButtons();
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/bzpage.js", line 455, in generateButtons
    this.createNewButton(newId, firstChr === "+", pkg, cmdIdx);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/bzpage.js", line 419, in createNewButton
    originalLocation.parentNode.insertBefore(newButton, originalLocation);
TypeError: originalLocation is null
}}}

**Comment by mcepl** [comment]
_Imported from trac issue 40.  Created by mcepl on 2010-08-15T14:01:26, last modified: 2010-08-16T22:20:17_

**Comment by mcepl** [comment]
_Trac comment by mcepl on 2010-08-16 22:20:17:_

Fixed in [3ace268]
