### ISSUE TITLE
bugs with alias instead of bug no break generating TimeSheets

### ISSUE THREAD

**Issue by mcepl** [mcepl/testissuesimport#45]
{{{
error: An exception occurred.
Traceback (most recent call last):
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/timer.js", line 58, in notify
    this._callback.apply(null, []);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/tab-browser.js", line 570, in 
    require("errors").catchAndLog(function(tab) options.onOpen(tab))(tab);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/errors.js", line 49, in 
    return callback.apply(this, arguments);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-jetpack-core-lib/tab-browser.js", line 570, in 
    require("errors").catchAndLog(function(tab) options.onOpen(tab))(tab);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/logger.js", line 120, in 
    bodyBuildCB.call(that, otherDoc.body);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/logger.js", line 128, in 
    this.timeSheetRecordsPrinter(body, this.store);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/logger.js", line 78, in 
    tmpArr.forEach(function(rec) {
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/logger.js", line 86, in 
    throw new Error("wrong record:\n" + rec.toSource() + "\n");
  File "", line 0, in Error
Error: wrong record:
["2010-08-20+bugzilla.redhat.com+NaN", {date:"2010-08-20T14:55:29.382Z", url:"https://bugzilla.redhat.com/show_bug.cgi?id=PyCObject", title:"Check/port usage of deprecation PyCObject_ API", comment:"adding bug 621887 as depending on it"}]
}}}

**Comment by mcepl** [comment]
_Imported from trac issue 45.  Created by mcepl on 2010-09-10T18:20:57, last modified: 2010-09-10T21:54:41_

**Comment by mcepl** [comment]
_Trac comment by mcepl on 2010-09-10 21:54:41:_

Fixed in [f2f034c9]
