### ISSUE TITLE
Fixing attachments doesn't work

### ISSUE THREAD

**Issue by mcepl** [mcepl/testissuesimport#73]
XMLRPC calls crashes:
{{{
error: An exception occurred.
Traceback (most recent call last):
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/timer.js", line 64, in notifyOnTimeout
    this._callback.apply(null, this._params);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/content/worker.js", line 64, in emitter
    emit.apply(scope, params);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/events.js", line 147, in _emit
    return this._emitOnObject.apply(this, args);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/events.js", line 177, in _emitOnObject
    listener.apply(targetObj, params);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/main.js", line 145, in 
    messageHandler(worker, msg);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/main.js", line 95, in messageHandler
    msg.data.params, function(ret) {
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/libbugzilla.js", line 283, in makeXMLRPCCall
    var urlObj = urlMod.URL(url);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/api-utils.js", line 69, in PublicCtor
    privateCtor.apply(obj, arguments);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/url.js", line 97, in URL
    var uri = newURI(url, base);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/url.js", line 51, in newURI
    throw new Error("malformed URI: " + uriStr);
Error: malformed URI: undefined
error: An exception occurred.
Traceback (most recent call last):
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/timer.js", line 64, in notifyOnTimeout
    this._callback.apply(null, this._params);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/content/worker.js", line 64, in emitter
    emit.apply(scope, params);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/events.js", line 147, in _emit
    return this._emitOnObject.apply(this, args);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/events.js", line 177, in _emitOnObject
    listener.apply(targetObj, params);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/main.js", line 145, in 
    messageHandler(worker, msg);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/main.js", line 95, in messageHandler
    msg.data.params, function(ret) {
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/libbugzilla.js", line 283, in makeXMLRPCCall
    var urlObj = urlMod.URL(url);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/api-utils.js", line 69, in PublicCtor
    privateCtor.apply(obj, arguments);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/url.js", line 97, in URL
    var uri = newURI(url, base);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/url.js", line 51, in newURI
    throw new Error("malformed URI: " + uriStr);
Error: malformed URI: undefined
error: An exception occurred.
Traceback (most recent call last):
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/timer.js", line 64, in notifyOnTimeout
    this._callback.apply(null, this._params);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/content/worker.js", line 64, in emitter
    emit.apply(scope, params);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/events.js", line 147, in _emit
    return this._emitOnObject.apply(this, args);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/events.js", line 177, in _emitOnObject
    listener.apply(targetObj, params);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/main.js", line 145, in 
    messageHandler(worker, msg);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/main.js", line 95, in messageHandler
    msg.data.params, function(ret) {
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-bugzilla-triage-lib/libbugzilla.js", line 283, in makeXMLRPCCall
    var urlObj = urlMod.URL(url);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/api-utils.js", line 69, in PublicCtor
    privateCtor.apply(obj, arguments);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/url.js", line 97, in URL
    var uri = newURI(url, base);
  File "resource://jid0-uxmbewgoltuuuqrhkhrr7hw3iqy-api-utils-lib/url.js", line 51, in newURI
    throw new Error("malformed URI: " + uriStr);
Error: malformed URI: undefined
info: Message: cmd = CreateButtons, data = [object Object]
info: onMessage - incoming : msg.cmd = CreateButtons
}}}

**Comment by mcepl** [comment]
_Imported from trac issue 73.  Created by mcepl on 2011-03-25T18:10:51, last modified: 2011-03-25T19:21:38_

**Comment by mcepl** [comment]
_Trac comment by mcepl on 2011-03-25 19:21:38:_

Fixed by [1876303]
